### PR TITLE
Update VERSION

### PR DESCRIPTION
**Pull request by gattytto**
Signed-off-by: Esteban Mañaricua <emanaricua@gmail.com>

### CODE REVIEW

**Comment by benoitf** [comment]
Hi, I'm not sure to follow why we need to use version 3.15 as dart image used is `2.10-dev` ?

**Comment by gattytto** [comment]
> Hi, I'm not sure to follow why we need to use version 3.15 as dart image used is `2.10-dev` ?

because the versioning follows the extension version number and not the upstream base image, or we would have different versions for sidecar and extension, as requested by @ericwill

**Comment by benoitf** [comment]
ok need to ping @ericwill because for example for java/python/ etc the sidecar image has the version of the embedded framework (like 11, 7, etc)

**Comment by gattytto** [comment]
https://github.com/che-dockerfiles/che-sidecar-flutter/pull/2#discussion_r490452840 this is the message @benoitf

**Comment by ericwill** [comment]
I think in this case it's a bit different:
* the flutter SDK changes versions often, it's not quite as stable as Java/Python/Node
* the SDK version names are confusing to read things like `1.22.0-12.0.pre-` -- `3.14.1-` is easier to read
* there is really only one extension that makes use of it

**Comment by benoitf** [comment]
Let's name it 1.22 if issue is just about shortness.
This image has no links to the vscode extension so dependency is in the reverse side
Or it needs to be named by it's vscode extension
Any vscode extensions or user needing dart could use these images so finding a vscode version is strange

**Pull request closed without merging**
